apiVersion: v1
kind: ReplicationController
metadata:
  name: logstash-kafka-es-rc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: vungle/logstash-kafka-es:2.2.0
        env:
        - name: ZK_CONNECT_LIST
          value: 1.2.3.4
        - name: KAFKA_TOPIC
          value: test-topic
        - name: ES_URL
          value: http://example.com/
        - name: ES_INDEX=test-index
